### ISSUE TITLE
Incorrect private URL

### ISSUE THREAD

**Issue by gilbox** [sourcegraph/sourcegraph-sublime#2]
Hi!

I modified the config to use a custom `SOURCEGRAPH_URL` URL, however when I try to `Sourcegraph: Open` it adds an extra path part (the git domain name) to the URL that shouldn't be there. 

ie: 

https://MY_SOURCEGRAPH_URL/git.domain.tld/company/repo@branch/path/to/file

instead of:

https://MY_SOURCEGRAPH_URL/company/repo@branch/path/to/file

iow, the `git.domain.tld` portion should not be there

**Comment by sqs** [comment]
Thanks for filing. This affects all repositories whose name on Sourcegraph doesn't match the Git remote URL (which is fairly common now). We will fix this in the next release of Sourcegraph (by the end of August), if not sooner.

Related: https://github.com/sourcegraph/sourcegraph-vscode/issues/8
