### ISSUE TITLE
Sourcegraph and SublimeText 3

### ISSUE THREAD

**Issue by davmaz** [sourcegraph/sourcegraph-sublime#30]
Right now Sourcegraph does not show up in Sublime Text. I know it "did" because I tried it a couple days ago. Afterwards my sublime text setup was totally hosed -- maybe my fault, but it did seem weird. Is it being held back by the Sublime Text maintainers for this reason?

**Comment by uforic** [comment]
Hey @davmaz , thanks for reporting this - I just double checked on my Sublime Text install, and was able to find it. One mistake I make a lot is forgetting to uninstall it before I can install it again.

Mind double-checking that the package is still not installed? Bummer to hear it didn't work out of the box. If you are able to get it installed again, let us know if it's still not working as expected and we can dig into details.

**Comment by davmaz** [comment]
Hello -
  Thanks for writing. I just tried it again and it seems to be working fine. On a side note, is there a way to select the font (or size, actually) that is used when the info is displayed in Chrome?

  Nice work!
Dave
________________________________________

**Comment by uforic** [comment]
Glad to hear that worked. Good call about the text, we are thinking of ways to make that editor feel more natural (larger text would help!). Thoughts on a WebView native app versus a browser window? Will close this out for now.
