### ISSUE TITLE
$GOBIN is not typically $GOROOT/bin/go

### ISSUE THREAD

**Issue by jostyee** [sourcegraph/sourcegraph-sublime#31]
According to https://golang.org/cmd/go/#hdr-Environment_variables , $GOBIN is `The directory where 'go install' will install a command.` , which means it usually sets to `$GOPATH/bin` , but this plugin demands setting this env to `$GOROOT/bin/go` to make it work.

**Comment by uforic** [comment]
Thanks for pointing this out @jostyee - unfortunately, it will be hard to change this behavior without breaking backwards compatibility. We are developing the second iteration of Sourcegraph for Sublime, (a major release), and so we can plan on changing the way we refer to GOBIN there. Will close this out for now, but thanks for reporting this!
